from pathlib import Path
from weasyprint import HTML

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "downloads" / "Etalon_Brand_Guide_2025.pdf"
OUTPUT.parent.mkdir(parents=True, exist_ok=True)

html = r'''<!doctype html>
<html lang="ru">
<head>
<meta charset="utf-8">
<style>
@font-face{font-family:Gilroy;src:url('fonts/Gilroy-Regular.ttf')}@font-face{font-family:Gilroy;src:url('fonts/Gilroy-Medium.ttf');font-weight:500}
@page{size:A4 landscape;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Gilroy,Arial,sans-serif;color:#1e242e;background:#f6f7fa}.page{width:297mm;height:210mm;padding:18mm 20mm;page-break-after:always;position:relative;overflow:hidden}.page:last-child{page-break-after:auto}.blue{background:#223e90;color:white}.eyebrow{font-size:11pt;letter-spacing:.18em;text-transform:uppercase}.cover h1{font-size:44pt;line-height:.96;font-weight:500;margin:45mm 0 9mm;max-width:220mm}.cover p{font-size:18pt;color:rgba(255,255,255,.75);max-width:170mm}.section-title{display:flex;align-items:center;gap:8mm;margin-bottom:12mm}.section-title span{font-size:11pt;color:#929aa8}.section-title i{display:block;width:12mm;height:.4mm;background:#aeb7c7;transform:rotate(-45deg)}h2{font-size:34pt;font-weight:500;margin:0 0 10mm}h3{font-size:18pt;font-weight:500;margin:0 0 3mm}.muted{color:#7b8493}.logo-grid{display:grid;grid-template-columns:1fr 1fr;gap:8mm}.logo-card{height:61mm;border:1px solid #dfe3eb;border-radius:6mm;background:white;padding:8mm;display:flex;align-items:center;justify-content:center;position:relative}.logo-card img{max-width:70%;max-height:30mm}.logo-card small{position:absolute;left:7mm;bottom:5mm;color:#7b8493}.palette{display:grid;grid-template-columns:repeat(5,1fr);gap:5mm}.swatch{height:118mm;border-radius:5mm;padding:7mm;display:flex;flex-direction:column;justify-content:flex-end}.swatch b{font-size:16pt}.swatch p{font-size:10pt;line-height:1.5;margin:3mm 0 0}.type-demo{display:grid;grid-template-columns:.8fr 1.2fr;gap:14mm}.big-aa{font-size:90pt;color:#223e90;line-height:1}.slogan{font-size:42pt;line-height:1.02;color:#223e90;margin:8mm 0}.body-copy{font-size:16pt;line-height:1.55;color:#596270}.rules{display:grid;grid-template-columns:1.15fr .85fr;gap:10mm}.safe{height:125mm;background:white;border:1px solid #dfe3eb;border-radius:6mm;display:flex;align-items:center;justify-content:center;position:relative}.safe img{width:55%}.safe:after{content:'';position:absolute;inset:25mm 35mm;border:1.2px dashed #9da6b5}.dont{background:white;border:1px solid #dfe3eb;border-radius:6mm;padding:9mm}.dont li{font-size:16pt;padding:5mm 0;border-top:1px solid #e2e5eb;list-style:none}.dont li:before{content:'×';color:#ff4d00;margin-right:5mm}.map-page img{position:absolute;left:-15mm;right:-15mm;bottom:-12mm;width:327mm;height:155mm;object-fit:contain}.map-page .copy{position:relative;z-index:2;max-width:130mm}.footer{position:absolute;bottom:9mm;right:20mm;font-size:9pt;color:#9aa2af}.blue .footer{color:rgba(255,255,255,.55)}
</style>
</head><body>
<section class="page blue cover"><div class="eyebrow">Группа «Эталон»</div><h1>Руководство<br>по фирменному стилю</h1><p>Логотипы, цвета, типографика, правила использования и готовые материалы.</p><div class="footer">Центр бренда · 2025</div></section>
<section class="page"><div class="section-title"><span>01</span><i></i><span>ОСНОВА БРЕНДА</span></div><h2>Логотипы</h2><div class="logo-grid"><div class="logo-card"><img src="assets/group-etalon.svg"><small>Группа «Эталон» · полная версия</small></div><div class="logo-card"><img src="assets/etalon-ru.svg"><small>Кириллический логотип</small></div><div class="logo-card"><img src="assets/etalon-en.svg"><small>Английский логотип</small></div><div class="logo-card"><img src="assets/symbol-etalon.svg"><small>Фирменный знак</small></div></div><div class="footer">Группа «Эталон»</div></section>
<section class="page blue"><div class="section-title"><span style="color:#b9c5e5">02</span><i style="background:#8298d1"></i><span>ВИЗУАЛЬНЫЙ ЯЗЫК</span></div><h2>Фирменные цвета</h2><div class="palette"><div class="swatch" style="background:#213a8f;border:1px solid #7184bd"><b>Синий</b><p>#213A8F<br>RGB 33 58 143<br>CMYK 100 85 0 0</p></div><div class="swatch" style="background:#1e242e"><b>Графитовый</b><p>#1E242E<br>RGB 30 36 46<br>CMYK 86 72 54 68</p></div><div class="swatch" style="background:#909cc7"><b>Синий 50%</b><p>#909CC7<br>RGB 144 156 199<br>CMYK 50 43 0 0</p></div><div class="swatch" style="background:#dee1ee;color:#223e90"><b>Синий 15%</b><p>#DEE1EE<br>RGB 222 225 238<br>CMYK 15 13 0 0</p></div><div class="swatch" style="background:#ff4d00"><b>Оранжевый</b><p>#FF4D00<br>RGB 255 77 0<br>CMYK 0 79 94 0</p></div></div><div class="footer">Группа «Эталон»</div></section>
<section class="page"><div class="section-title"><span>03</span><i></i><span>ТИПОГРАФИКА</span></div><h2>Gilroy</h2><div class="type-demo"><div><div class="big-aa">Аа</div><p class="muted">Gilroy Medium<br>для заголовков и акцентов</p></div><div><div class="slogan">Создаем<br>пространство<br>для жизни</div><p class="body-copy">Gilroy Regular используется для основного текста. Типографика должна оставаться ясной, современной и легко читаемой во всех коммуникациях.</p></div></div><div class="footer">Группа «Эталон»</div></section>
<section class="page"><div class="section-title"><span>04</span><i></i><span>ПРАВИЛА</span></div><h2>Охранное поле</h2><div class="rules"><div class="safe"><img src="assets/etalon-ru.svg"></div><div class="dont"><h3>Не допускается</h3><ul><li>Искажать пропорции</li><li>Менять фирменные цвета</li><li>Добавлять тени и эффекты</li><li>Поворачивать или наклонять</li></ul></div></div><div class="footer">Группа «Эталон»</div></section>
<section class="page map-page"><div class="copy"><div class="section-title"><span>05</span><i></i><span>ГЕОГРАФИЯ</span></div><h2>Карта присутствия</h2><p class="body-copy">Используйте чистую векторную карту без точек и подписей. Территории присутствия выделяются фирменным синим.</p></div><img src="assets/regions-map.svg"><div class="footer">Группа «Эталон»</div></section>
</body></html>'''

HTML(string=html, base_url=str(ROOT)).write_pdf(str(OUTPUT))
print(OUTPUT)
